apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wasmcloud
  namespace: argocd
spec:
  project: default
  source:
    chart: charts/runtime-operator
    repoURL: ghcr.io/ericgregory
    targetRevision: 0.1.0
    helm:
      values: |
        runtime:
          image:
            repository: cosmonic-labs/wash-host
            tag: "canary"
          hostGroups:
            - name: public-ingress
              replicas: 1
              service:
                type: NodePort
              http:
                enabled: true
                port: 80
                nodePort: 30950
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m" # 0.25 CPU cores
                limits:
                  memory: "512Mi"
                  cpu: "500m" # 0.5 CPU cores
            - name: private-ingress
              replicas: 1
              service:
                type: ClusterIP
              http:
                enabled: true
                port: 80
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m" # 0.25 CPU cores
                limits:
                  memory: "512Mi"
                  cpu: "500m" # 0.5 CPU cores
            - name: default
              replicas: 1
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m" # 0.25 CPU cores
                limits:
                  memory: "512Mi"
                  cpu: "500m" # 0.5 CPU cores
  destination:
    name: 'in-cluster'
    namespace: wasmcloud-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m